version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.13.0
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: eshopy_test

    working_directory: ~/repo

    steps:
      - checkout
      - run: cd server && npm install
      - run: cd server && npm run migration:test
      - run: cd server && npm run test:ci
